name: Main branch Maven Build, test and Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Show default environment variables
      run: |
        echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
        echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"
        echo "github.ref_name: ${{ github.ref_name }}"
        echo "github.ref: ${{ github.ref }}"

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-        

    - name: Build with Maven
      run: mvn -e -B verify --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: ./target/site/jacoco/jacoco.csv
        badges-directory: ./badges
        coverage-badge-filename: jacoco-badge-${{ github.ref_name }}.svg
    
    - name: Upload badge (JaCoCo) to Gist
      uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gistURL: https://gist.github.com/jajir/a613341fb9d9d0c6a426b42a714700b7
        file: ./badges/jacoco-badge-${{ github.ref_name }}.svg
          
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      id: test-results
      if: always()
      with:
        files: |
          target/surefire-reports/**/*.xml
          target/surefire-reports/**/*.trx
          target/surefire-reports/**/*.json

    - name: Set badge color
      shell: bash
      run: |
        case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
          success)
            echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
            ;;
          failure)
            echo "BADGE_COLOR=800000" >> $GITHUB_ENV
            ;;
          neutral)
            echo "BADGE_COLOR=696969" >> $GITHUB_ENV
            ;;
        esac
    
    - name: Create badge
      uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8
      with:
        label: Tests
        status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
        color: ${{ env.BADGE_COLOR }}
        path: badge-${{ github.ref_name }}.svg
    
    - name: Upload badge (test results) to Gist
      uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gistURL: https://gist.github.com/jajir/a613341fb9d9d0c6a426b42a714700b7
        file: badge-${{ github.ref_name }}.svg

    - name: OWASP vulnerabilities - count
      id: vuln
      run: |
        VULN_COUNT=$(jq '[.dependencies[] | select(.vulnerabilities and (.vulnerabilities | length > 0)) | .vulnerabilities[]] | length' target/dependency-check-report.json)
        echo "OWASP Vulnerabilities count: $VULN_COUNT"
        echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV

    - name: OWASP vulnerabilities - Generate badge
      uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8
      with:
        label: 'OWASP Vulnerabilities'
        status: ${{ env.VULN_COUNT }}
        color: 31c653
        path: badge-owasp-${{ github.ref_name }}.svg

    - name: OWASP vulnerabilities - Upload badge to Gist
      uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gistURL: https://gist.github.com/jajir/a613341fb9d9d0c6a426b42a714700b7
        file: badge-owasp-${{ github.ref_name }}.svg
            

